# Generated by Django 4.2 on 2023-09-26 17:26

import datetime
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tag_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 17, 26, 9, 430120, tzinfo=datetime.timezone.utc)),
        ),
    ]

