# Generated by Django 4.2 on 2023-10-08 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 6, 43, 55, 989311, tzinfo=datetime.timezone.utc)),
        ),
    ]
