# Generated by Django 4.2 on 2023-11-07 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 20, 0, 17, 340798, tzinfo=datetime.timezone.utc)),
        ),
    ]
